---
- id: 1
  name: keppler
  url: "/keppler"
  method: GET
  active: true
  format_result: HTML
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 14:27:16.678305000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-10-25 10:27:16.678305000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 14:27:16.678305000 Z
    zone: *1
    time: 2018-10-25 10:27:16.678305000 Z
- id: 2
  name: index
  url: "/"
  method: GET
  active: true
  format_result: HTML
  position: 2
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 14:29:40.593057000 Z
    zone: *1
    time: 2018-10-25 10:29:40.593057000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 14:29:40.593057000 Z
    zone: *1
    time: 2018-10-25 10:29:40.593057000 Z
- id: 3
  name: home
  url: "/home"
  method: GET
  active: true
  format_result: HTML
  position: 3
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 15:25:43.514449000 Z
    zone: *1
    time: 2018-10-25 11:25:43.514449000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 15:25:43.514449000 Z
    zone: *1
    time: 2018-10-25 11:25:43.514449000 Z
- id: 4
  name: show_table
  url: "/table/:id"
  method: GET
  active: true
  format_result: HTML
  position: 4
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 17:34:17.915122000 Z
    zone: *1
    time: 2018-10-25 13:34:17.915122000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 17:34:17.915122000 Z
    zone: *1
    time: 2018-10-25 13:34:17.915122000 Z
