---
- id: 8
  key: login
  value: Entrar
  language_id: 1
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 15:34:49.089953000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-10-25 11:34:49.089953000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 15:34:49.089953000 Z
    zone: *1
    time: 2018-10-25 11:34:49.089953000 Z
- id: 9
  key: email
  value: Correo
  language_id: 1
  position: 2
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 15:34:49.105898000 Z
    zone: *1
    time: 2018-10-25 11:34:49.105898000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 15:34:49.105898000 Z
    zone: *1
    time: 2018-10-25 11:34:49.105898000 Z
- id: 10
  key: password
  value: Contraseña
  language_id: 1
  position: 3
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 15:34:49.122626000 Z
    zone: *1
    time: 2018-10-25 11:34:49.122626000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 15:34:49.122626000 Z
    zone: *1
    time: 2018-10-25 11:34:49.122626000 Z
- id: 11
  key: logout
  value: Cerrar sesión
  language_id: 1
  position: 4
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 15:34:49.139682000 Z
    zone: *1
    time: 2018-10-25 11:34:49.139682000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-25 15:34:49.139682000 Z
    zone: *1
    time: 2018-10-25 11:34:49.139682000 Z
