menu:
  keppler_comanda_control:
    name: Comanda Control
    current: ['/']
    url_path: /
    icon: layers
    model: User
    submenu:
      - tables:
          name: tables
          url_path: /admin/comanda_control/tables
          icon: layers
          current: ['/admin/comanda_control/tables']
          model: KepplerComandaControl::Table

      # - new:
      #     name: + Add new module
      #     url_path: /url_path
      #     current: ['/current_path']
      #     enviroment: development
      #     model: User